### ISSUE TITLE
modals on ultimate-guitar.com

### ISSUE THREAD

**Issue by ghost** [AliasIO/demodal#18]
There are at least two obnoxious time-delayed modals that appear on the popular song chords website ultimate-guitar.com:

Example link: https://tabs.ultimate-guitar.com/tab/in-extremo/ai-vis-lo-lop-chords-1101970

The first is a sign-up modal that appears after about 20 seconds:
![Screenshot from 2023-06-16 00-27-14](https://github.com/AliasIO/demodal/assets/134243032/7a1dd478-18fd-4b6f-a8b6-7c664f926291)

The second is an app advertising modal that appears after about about 60 seconds:
![Screenshot_20230616-005434_DuckDuckGo](https://github.com/AliasIO/demodal/assets/134243032/84c7adc4-b96d-4652-9be7-64d0214e2385)

**Comment by AliasIO** [comment]
This definition should take care of the sign up prompt. I haven't seen the second modal come up.

```
{
  "tabs.ultimate-guitar.com": {
    "body div[style*='z-index']": "removeIf 'Sign up'"
  }
}
```

**Comment by Fennecine** [comment]
Thank you!

**Comment by ghost** [comment]
Thank you!
