### ISSUE TITLE
modal not blocked on celticseasalt.com

### ISSUE THREAD

**Issue by ghost** [AliasIO/demodal#19]
The modal on this website isn't being blocked: https://www.celticseasalt.com/
Instructions for replication: Enter the site, wait about 5 seconds, and it pops up.

![Screenshot from 2023-07-29 02-31-56](https://github.com/AliasIO/demodal/assets/134243032/66b8cae8-e880-4d7f-92ad-b8e6466ea4d7)

I modified your code you suggested to me from my previous issue into this, but it doesn't remove it:
```
{
  "celticseasalt.com": {
    "body div[style*='z-index']": "removeIf 'Join'"
  }
}
```

By the way, is reporting unblocked modals here in the issues page the way we improve Demodal for future versions?

Thanks either way. Cookie and newsletter modals are the bane of my internet experience and your addon helps restore some sanity.

**Comment by AliasIO** [comment]
Try this:

```
{
  "celticseasalt.com": {
    ".notice1LD": "remove"
  }
}
```

**Comment by ghost** [comment]
Thank you.
