### ISSUE TITLE
Simply Wall Street's paywall is not blocked

### ISSUE THREAD

**Issue by zincurat** [AliasIO/demodal#3]
Unfortunately instructions for me are unclear how to create rule for removing paywall, so I ask somebody to do this. 

Link (it's showing paywall only when stock is chosen) - https://simplywall.st/stocks/us/tech/nasdaq-aapl/apple

![image](https://user-images.githubusercontent.com/75274850/150669350-1361d1a5-5079-4dfa-b2fa-6d85ddda1e90.png)

**Comment by AliasIO** [comment]
Added in 2db34ca15952075919ea74dd3901fe179c232c27, thanks!

**Comment by zincurat** [comment]
Thanks for answer, unfortunately nothing changed :( Version 1.0.2 Last updated 24 Jan

**Comment by AliasIO** [comment]
Strange, it does work for me in both Firefox and Chrome. The window pops up for a moment and gets removed. Does refreshing the page do anything? You didn't accidentally allow modals on the website in the extension popup? Does the extension report any blocked modals?

**Comment by zincurat** [comment]
I am very sorry, my mistake. I indeed allowed modals on website. Thank you

**Comment by AliasIO** [comment]
No worries, I'm glad it's working after all. :)
