### ISSUE TITLE
The Wall Street Journal

### ISSUE THREAD

**Issue by samuraikid0** [AliasIO/demodal#5]
The wall street journal
paywall still there

ex:
`https://www.wsj.com`
`https://www.wsj.com/articles/states-file-new-suits-against-google-over-location-tracking-11643037890`

Great addon !

**Comment by AliasIO** [comment]
Unfortunately the WSJ paywall modifies the page server-side. We can remove the modal and gradient but you'd still only be able to see the first couple of paragraphs of the article:

<img width="896" alt="Screen Shot 2022-01-27 at 8 01 14 am" src="https://user-images.githubusercontent.com/77259/151246320-697f381b-990b-4b1d-80d3-288d486a8d25.png">

**Comment by samuraikid0** [comment]
Ok understood 
Thanks !
